#pragma kernel CSMain

RWTexture2D<float4> Result;

struct RevealerData
{
    float2 position;
    float radius;
};

StructuredBuffer<RevealerData> _Revealers;

int _TextureSize;
int _RevealerCount;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= _TextureSize || id.y >= _TextureSize)
        return;

    float visible = 0.0;

    float2 pixelPos = float2(id.x, id.y);

    for (int i = 0; i < _RevealerCount; i++)
    {
        float2 diff = pixelPos - _Revealers[i].position;

        float distSqr = dot(diff, diff);

        if (distSqr <= (_Revealers[i].radius * _Revealers[i].radius))
        {
            visible = 1.0;
            break;
        }
    }

    float4 previous = Result[id.xy];

    float explored = max(previous.g, visible);
    visible = max(visible, previous.g);

    Result[id.xy] = float4(visible, explored, 0.0, 1.0);
}